import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Navegador} from "./components/navegador";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "One Family Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="p-4 text-center">
        <Navegador />
      </header>
      {children}
      </body>
    </html>
  );
}
